# Generated by Django 3.2.2 on 2021-05-10 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webreceitas', '0002_rename_data_receita_receita_data_receitas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='data_receitas',
        ),
        migrations.AddField(
            model_name='receita',
            name='data_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
