# Generated by Django 3.2.2 on 2021-05-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webreceitas', '0004_rename_data_receita_receita_data_receitas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='data_receitas',
            new_name='data_receita',
        ),
    ]
