# Generated by Django 3.2.2 on 2021-05-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webreceitas', '0005_rename_data_receitas_receita_data_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='tempo_preparo',
            field=models.IntegerField(),
        ),
    ]
