# Generated by Django 3.2.2 on 2021-05-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webreceitas', '0007_receita_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
